name: 'Package source code & dependencies'
description: 'Package source code & dependencies for SAST & SCA scans'
author: 'Fortify'
runs:
  using: composite
  steps:
    - uses: edguerreros/github-action/setup@main
      with:
        export-path: false
        sc-client: action-default
    - uses: edguerreros/github-action/internal/run@main
      with: 
        cmd: '"${SC_CLIENT_CMD}" package ${EXTRA_PACKAGE_OPTS} -o package.zip'
branding:
  icon: 'shield'
  color: 'blue'

